services:
  mysqldb:
    container_name: mysql-db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: ecomdb
      # MYSQL_USER: klu
      # MYSQL_PASSWORD: klu
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql   # volume added here

  backend:
    container_name: springboot
    build:
      context: ./ECOM-BACKEND
      dockerfile: ../ECOM-FULLSTACK/backend.Dockerfile
    ports:
      - "2025:2000"
    depends_on:
      - mysqldb
    restart: on-failure

  frontend:
    container_name: react
    build:
      context: ./ECOM-FRONTEND
      dockerfile: ../ECOM-FULLSTACK/frontend.Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

# Declare volumes at the bottom
volumes:
  mysql-data: